server:
  port: 8090

# DataSource Config
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:h2:mem:test
#    username: root
#    password: test

#swagger 启用
swagger:
  enable: true
  basePackage: com.eyesfree.weibo
  info:
    title: API文档
    description: API文档
    version: 1.0
    serviceUrl: http://zzfx.hoptest.haier.net

